name: Build Mercurial
run-name: Build Mercurial ${{ inputs.hg-version }}

on:
  # Run manually
  workflow_dispatch:
    inputs:
      hg-version:
        description: 'Mercurial version to build'
        required: false
        type: string
        default: '6.5.1'

jobs:
  build-python:
    # Use specific Ubuntu version rather than ubuntu-latest, so we can control when to upgrade the runner
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install Python setuptools
      run: pip install setuptools
    - name: Checkout Mercurial
      run: hg clone https://repo.mercurial-scm.org/hg
    - name: Checkout hg version to build
      run: hg checkout "${VER}"
      working-directory: hg
      env:
        VER: ${{ inputs.hg-version }}
    - name: Build Mercurial
      run: make local
      working-directory: hg
    - name: Delete .hg folder prior to upload
      run: rm -rf .hg
      working-directory: hg
    - name: Upload Mercurial build results
      uses: actions/upload-artifact@v4
      with:
        name: hg-for-python-${{ matrix.python-version }}
        path: |
          hg/contrib
          hg/COPYING
          hg/hg
          hg/hgdemandimport
          hg/hgext
          hg/mercurial
        if-no-files-found: error

  combine:
    runs-on: ubuntu-latest
    needs: build-python
    steps:

    - name: Combine Mercurial builds
      uses: actions/download-artifact@v4
      with:
        path: .
        pattern: hg-for-python-*
        merge-multiple: true

    - name: Upload combined build
      uses: actions/upload-artifact@v4
      with:
        name: mercurial-${{ inputs.hg-version }}
        path: .
        if-no-files-found: error
