# This is a basic workflow to help you get started with Actions

name: Nuget-CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Cancel any workflow jobs running if the PR is re-triggered
concurrency:
  group: ci-${{ github.head_ref }}-group
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      with:
        fetch-depth: 0
    - name: Set Beta Version
      if: github.event_name != 'push'
      run: echo "release-suffix=-beta" >> $GITHUB_ENV
    - name: Set Release Version
      if: github.event_name == 'push'
      run: echo "release-suffix=." >> $GITHUB_ENV

    - name: Nuget pack
      run: dotnet msbuild -target:Build build/SIL.Chorus.Mercurial.proj -property:PreRelease=${{ env.release-suffix }} -property:BuildCounter=${{ github.run_number }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
      with:
        name: packages
        path: ./**/*.nupkg
        if-no-files-found: error

    - name: Publish nuget packages
      if: github.event_name == 'push'
      run: nuget push **/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{ secrets.SILLSDEV_PUBLISH_NUGET_ORG }}
